name: Create PDF Release

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on version tags (e.g., v1.0.0)
  workflow_dispatch: {}

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Compile the LaTeX files using Docker
    - name: Compile Barclay's Catechism
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/books/barclay-catechism \
          texlive/texlive \
          pdflatex -interaction=nonstopmode main.tex
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/books/barclay-catechism \
          texlive/texlive \
          pdflatex -interaction=nonstopmode main.tex

    - name: Compile Barclay's Confession
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/books/barclay-confession \
          texlive/texlive \
          pdflatex -interaction=nonstopmode main.tex
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/books/barclay-confession \
          texlive/texlive \
          pdflatex -interaction=nonstopmode main.tex

    # Step 3: Rename the PDFs
    - name: Rename Barclay's Catechism PDF
      run: |
        mv books/barclay-catechism/main.pdf barclay-catechism-thought-for-thought.pdf

    - name: Rename Barclay's Confession PDF
      run: |
        mv books/barclay-confession/main.pdf barclay-confession-thought-for-thought.pdf

    # Step 4: Create a Release and Upload the Assets
    - name: Create Release and Upload Assets
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: |
          barclay-catechism-thought-for-thought.pdf
          barclay-confession-thought-for-thought.pdf