name: Create PDF Release

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on version tags (e.g., v1.0.0)
  workflow_dispatch: {}

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Set up LaTeX environment
    - name: Set up LaTeX
      uses: dante-ev/latex-action@v2
      with:
        extra_system_packages: "texlive-latex-extra texlive-fonts-recommended"  # Add any necessary LaTeX packages

    # Step 3: Compile the LaTeX file
    - name: Compile LaTeX file
      run: |
        latexmk -f -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode books/barclay-catechism/main.tex

    # Step 4: Display LaTeX log file
    - name: Display LaTeX log
      run: |
        cat books/barclay-catechism/main.log

    # Step 5: Rename the PDF
    - name: Rename PDF
      run: |
        mv books/barclay-catechism/main.pdf "Barclay's Catechism Thought-for-Thought.pdf"

    # Step 6: Create Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }} # Use the tag that triggered the workflow
        release_name: "Release ${{ github.ref_name }}"
        draft: false
        prerelease: false
        body: |
          This release includes the compiled PDF of Barclay's Catechism.

    # Step 7: Upload Release Asset
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "Barclay's Catechism Thought-for-Thought.pdf"
        asset_name: "Barclay's Catechism Thought-for-Thought.pdf"
        asset_content_type: application/pdf
