name: Create PDF Release

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on version tags (e.g., v1.0.0)
  workflow_dispatch: {}

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Compile the LaTeX file using Docker
    - name: Compile LaTeX file
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/books/barclay-catechism \
          texlive/texlive \
          pdflatex -interaction=nonstopmode main.tex

    # Step 3: Rename the PDF
    - name: Rename PDF
      run: |
        mv books/barclay-catechism/main.pdf "Barclay's Catechism Thought-for-Thought.pdf"

    # Step 4: Create Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }} # Use the tag that triggered the workflow
        release_name: "Release ${{ github.ref_name }}"
        draft: false
        prerelease: false
        body: |
          This release includes the compiled PDF of Barclay's Catechism.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass the token here

    # Step 5: Upload Release Asset
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "Barclay's Catechism Thought-for-Thought.pdf"
        asset_name: "Barclay's Catechism Thought-for-Thought.pdf"
        asset_content_type: application/pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass the token here
