name: Create PDF Release

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on version tags (e.g., v1.0.0)
  workflow_dispatch: {}

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Cache TeX Live installation
    - name: Cache TeX Live
      id: texlive-cache
      uses: actions/cache@v3
      with:
        path: /usr/local/texlive
        key: texlive-${{ runner.os }}-${{ hashFiles('**/books/barclay-catechism/main.tex') }}
        restore-keys: texlive-${{ runner.os }}-

    # Step 3: Install TeX Live if not cached
    - name: Install TeX Live
      if: steps.texlive-cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    # Step 4: Compile the LaTeX file
    - name: Compile LaTeX file
      run: |
        pdflatex -output-directory=books/barclay-catechism books/barclay-catechism/main.tex

    # Step 5: Rename the PDF
    - name: Rename PDF
      run: |
        mv books/barclay-catechism/main.pdf "Barclay's Catechism Thought-for-Thought.pdf"

    # Step 6: Create Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }} # Use the tag that triggered the workflow
        release_name: "Release ${{ github.ref_name }}"
        draft: false
        prerelease: false
        body: |
          This release includes the compiled PDF of Barclay's Catechism.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass the token here

    # Step 7: Upload Release Asset
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "Barclay's Catechism Thought-for-Thought.pdf"
        asset_name: "Barclay's Catechism Thought-for-Thought.pdf"
        asset_content_type: application/pdf
