name: Create PDF Release

on:
  push:
    workflow_dispatch
    tags:
      - 'v*' # Trigger the workflow on version tags (e.g., v1.0.0)

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Set up LaTeX environment
    - name: Set up LaTeX
      uses: dante-ev/latex-action@edge

    # Step 3: Compile the LaTeX file
    - name: Compile LaTeX file
      run: |
        pdflatex -output-directory=books/barclay-catechism/main.pdf books/barclay-catechism/main.tex

    # Step 4: Rename the PDF
    - name: Rename PDF
      run: |
        mv books/barclay-catechism/main.pdf "Barclay's Catechism Thought-for-Thought.pdf"

    # Step 5: Upload the PDF as a release asset
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }} # Use the tag that triggered the workflow
        release_name: "Release ${{ github.ref_name }}"
        draft: false
        prerelease: false
        body: |
          This release includes the compiled PDF of Barclay's Catechism.

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "Barclay's Catechism Thought-for-Thought.pdf"
        asset_name: "Barclay's Catechism Thought-for-Thought.pdf"
        asset_content_type: application/pdf
